server:
  port: 8080
app:
  api-prefix: /api/v1
spring:
  application:
    name: gateway-service
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}

  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            # Trong 1s sẽ có 10 token được cấp phát
            redis-rate-limiter.replenishRate: 10
            # Số lượng token tối đa trong 1s
            redis-rate-limiter.burstCapacity: 20
            redis-rate-limiter.requestedTokens: 1
      #        - StripPrefix=1 # Remove prefix /api-gateway from request path
        - name: Retry
          args:
            retries: 2
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
            methods: GET,POST,PUT,DELETE
            backoff:
              firstBackoff: 3000ms
              maxBackoff: 5000ms
              factor: 1
              basedOnPreviousValue: false
            jitter:
              randomFactor: 0.5
            timeout: 100ms
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=${app.api-prefix}/products/**,${app.api-prefix}/categories/**
          filters:
            - PreserveHostHeader
            - StripPrefix=2 # Remove prefix /api/v1 from request path
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=${app.api-prefix}/orders/**,${app.api-prefix}/order-details/**
          filters:
            - StripPrefix=2 # Remove prefix /api/v1 from request path
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/account/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/carts/**,/api/cart-items/**
          # Config rate limit for service product-service
          filters:
            #            - name: CircuitBreaker
            #              args:
            #                name: default
            #                fallbackUri: forward:/fallback/product-service
eureka:
  instance:
#    hostname: ${HOST_IP_ADDRESS}
    hostname: ${HOST_IP_ADDRESS:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
      register-with-eureka: true
      fetch-registry: true
management:
  endpoint:
    health:
      show-details: always
