server:
  port: 9292
  # Datasource configuration
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIA_DB_ORDER_SERVICE}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  # SQL script to initialize the database
  logging:
    level:
      org.hibernate.SQL: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      root: INFO
      com.backend.orderservice: INFO
  sql:
    init:
    # Only run the script for first time
    #      mode: always
#      mode: never
#      data-locations: classpath:/sql/data.sql
gateway:
  service:
    url: ${GATEWAY_SERVICE_URL:http://localhost:8080}
#  data:
#    rest:
#      base-path: /api/v1